
###

GET http://localhost:4000/

###

GET http://localhost:4000/post
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NmIxZmVlYmQ5M2RmYmYwMjgzOTIxMSIsImlhdCI6MTY4NDc0MzgyOCwiZXhwIjoxNjg0NzY5MDI4fQ.I830PJ7jrQ9VJ0dUp2-UsEg5Pcwmucbej_GefW3GYl0

###

GET http://localhost:4000/post/643ef7b9d73feddefacccf60

###

POST http://localhost:4000/post
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NmIxZmVlYmQ5M2RmYmYwMjgzOTIxMSIsImlhdCI6MTY4NDc0MzgyOCwiZXhwIjoxNjg0NzY5MDI4fQ.I830PJ7jrQ9VJ0dUp2-UsEg5Pcwmucbej_GefW3GYl0
Content-Type: application/json

{
    "message": "this is my authorized new post",
    "sender": "or"
}

###

GET http://localhost:4000/travel
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NmIxZmVlYmQ5M2RmYmYwMjgzOTIxMSIsImlhdCI6MTY4NDc0MzgyOCwiZXhwIjoxNjg0NzY5MDI4fQ.I830PJ7jrQ9VJ0dUp2-UsEg5Pcwmucbej_GefW3GYl0

###

GET http://localhost:4000/travel/643ef7b9d73feddefacccf60

###

POST http://localhost:4000/travel
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NmIxZmVlYmQ5M2RmYmYwMjgzOTIxMSIsImlhdCI6MTY4NDc0MzgyOCwiZXhwIjoxNjg0NzY5MDI4fQ.I830PJ7jrQ9VJ0dUp2-UsEg5Pcwmucbej_GefW3GYl0
Content-Type: application/json

{
    "message": "this is my authorized new travel",
    "sender": "or"
}

###

POST http://localhost:4000/auth/register
Content-Type: application/json

{
    "email": "or@gmail.com",
    "password": "1234567"
}

###

POST http://localhost:4000/auth/login
Content-Type: application/json

{
    "email": "or@gmail.com",
    "password": "1234567"
}

###

GET http://localhost:4000/auth/logout
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NmIxZmVlYmQ5M2RmYmYwMjgzOTIxMSIsImlhdCI6MTY4NDc0MzgyOH0.Lx3lbf7PEikehXZSHA1L6kd6RrhW35fwzbbdqKm5LJ8
// refresh token ^^

###