
###

GET http://localhost:4000/

###

GET http://localhost:4000/post

###

GET http://localhost:4000/post/643ef7b9d73feddefacccf60

###

POST http://localhost:4000/post
Content-Type: application/json

{
    "message": "this is my new message",
    "sender": "Idan"
}